language: node_js
node_js: "8"

# Cache local yarn packages
cache: yarn

# Preinstall saucelab on the machine
addons:
  sauce_connect: true

# Install dependencies
install: yarn

# Run type check and tests
script:
  - yarn type
  - yarn test -- --coverage
  - yarn test:integration